### ISSUE TITLE
Lock Timeout error

### ISSUE THREAD

**Issue by detj** [cshum/levi#22]
`.put()`-in data from a large array containing objects, throws `Lock timeout` error after processing around 800-900 items. I'm assuming the number will vary from machine to machine.

```js
const users = levi('db/users')
const userdata = [{...}, {...}]; // large array

users
  .use(levi.tokenizer())
  .use(levi.stemmer())
  .use(levi.stopword())

userdata.forEach((val, key) => {
  users.put(key, val, (err) => {
    if (err) {
      console.error(err)
      if (err.stack) console.log(err.stack)
      return
    }

    console.log(`${key} was added in db`)
  })
})
```

```
{ [TIMEOUT: Lock timeout.]
  code: 408,
  name: 'TIMEOUT',
  message: 'Lock timeout.',
  TIMEOUT: true,
  error: true }
```

```
Error
    at Object.<anonymous> (/Users/detj/tmp/levi-try/node_modules/2pl/error.js:13:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/detj/tmp/levi-try/node_modules/2pl/index.js:3:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

The error seems to be coming from the https://github.com/cshum/2pl package.

**Comment by cshum** [comment]
@detj If you try to wrap some flow control (say promise sequence, or any async library you prefer), does it solves the problem?

```js
var promises = Promise.resolve()
userdata.forEach((val, key) => {
  promises = promises.then(function () {
    return users.put(key, val).then(() => {
      console.log(`${key} was added in db`)
    }, (err) => {
      console.error(err)
      if (err.stack) console.log(err.stack)
    })
  })
})
```

**Comment by detj** [comment]
@cshum It did solve it. 👍
