### ISSUE TITLE
npm run dev error! 

### ISSUE THREAD

**Issue by AdonisInveste** [cshum/levi#25]
When I used `npm run dev` to run my program it keeps giving me this error. I deleted and git cloned the repository again.

I used `npm install` to get all the required packages.

it is still giving me the following error. 
```
eloiim:levi-frontend iivri.andre$ npm run dev 

> levi@1.0.0 dev /Users/iivri.andre/levi-frontend
> node build/dev-server.js

> Starting dev server...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at Server.listen (net.js:1390:5)
    at EventEmitter.listen (/Users/iivri.andre/levi-frontend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/iivri.andre/levi-frontend/build/dev-server.js:84:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! levi@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the levi@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the levi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs levi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls levi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iivri.andre/levi-frontend/npm-debug.log
```

**Comment by derhuerst** [comment]
You already have a process running on port 8080.
